use std::ops::{Deref, DerefMut};

/// Marks a type as a handle to a parent test.
///
/// Implemented automatically by the `#[testscribe]` macro for the marker type it generates
/// (the PascalCase version of the test function name). `Value` is the test function's
/// return type — the state that child tests receive through [`Given`].
///
/// You should never need to implement this trait manually.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a parent test",
    label = "expected the marker type of a parent test",
    note = "`Given<P>` takes the PascalCase marker type that `#[testscribe]` generates from a parent test function's name (e.g. `fn cart_created` -> `Given<CartCreated>`), not an arbitrary type"
)]
pub trait ParentTest {
    /// The state returned by the parent test function.
    type Value;
}

impl ParentTest for () {
    type Value = ();
}

/// Test argument that receives the state returned by the parent test.
///
/// Declaring a `Given<Parent>` argument makes a test a child of `Parent` — the marker type
/// generated by `#[testscribe]` for the parent test function. The framework executes the
/// parent first and passes its returned state here.
///
/// The inner value can be accessed in several ways:
/// - by dereferencing: `*state` (both read and write, via [`Deref`]/[`DerefMut`])
/// - by destructuring in the argument position: `Given(state): Given<Parent>`, or pattern-match
///   the state directly, e.g. `Given(Cart { id, items }): Given<Parent>`. This binds the inner
///   value (or its fields) *by value*, which is the way to get owned access — needed for
///   non-[`Copy`] state, or to take `&mut` to individual fields — without moving out of `*state`.
/// - by taking ownership with [`into_inner`](Given::into_inner), e.g. to return a modified
///   state from the test
///
/// ```ignore
/// #[testscribe]
/// fn another_6_is_added(mut state: Given<OneAndTwoIsAdded>) -> i32 {
///     *state += 6;
///     then!(*state => sum).eq(9);
///     state.into_inner()
/// }
/// ```
pub struct Given<P>(pub P::Value)
where
    P: ParentTest;

impl<P> Given<P>
where
    P: ParentTest,
{
    /// Consumes the wrapper and returns the parent state by value.
    pub fn into_inner(self) -> P::Value {
        self.0
    }
}

impl<P> Deref for Given<P>
where
    P: ParentTest,
{
    type Target = P::Value;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<P> DerefMut for Given<P>
where
    P: ParentTest,
{
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
